site_name: NeuralNetworks
site_url: https://xXxFetraxXx.github.io/NeuralNetworks
repo_url: https://github.com/xXxFetraxXx/NeuralNetworks
site_description: "Multi-Layer Perceptrons with multi-Fourier encoding and variable learning rate"
site_author: "Alexandre Brun"
theme:
  name: readthedocs

nav:

  - Accueil: index.md

  - Dependances:
      - torch: https://pypi.org/project/torch/
      - numpy: https://pypi.org/project/numpy/
      - matplotlib: https://pypi.org/project/matplotlib/

  - Liens:
      - PyPI: https://pypi.org/project/NeuralNetworks/
      - Source: https://github.com/xXxFetraxXx/NeuralNetworks

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: true