site_name: NeuralNetworks
site_url: https://xXxFetraxXx.github.io/NeuralNetworks/
use_directory_urls: true
repo_name: NeuralNetworks
repo_url: https://github.com/xXxFetraxXx/NeuralNetworks
site_description: "Multi-Layer Perceptrons with multi-Fourier encoding and variable learning rate"
site_author: "Alexandre Brun"

extra_css:
  - stylesheets/extra.css

theme:
  logo: assets/MainLogo.png
  favicon: assets/MainLogo.png
  name: material
  features:
    - header.autohide
    - content.tabs.link
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.annotations
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:

  - Accueil: index.md
  - Prise en main:
      - Installation: dependences/install.md
      - Dependences: dependences/dependences.md
      - Support: dependences/support.md
  - Modèles:
      - NeuralNetworks.Module:
          - module/index.md
          - NeuralNetworks.Module.save: module/save.md
          - NeuralNetworks.Module.load: module/load.md
          - NeuralNetworks.Module.save_onnx: module/save_onnx.md
          - Modules préfabriqués:
              - NeuralNetworks.MLP: module/mlp.md
              - NeuralNetworks.VAE: module/vae.md
  - Trainer:
      - NeuralNetworks.Trainer:
          - Trainer/index.md
          - NeuralNetworks.Trainer.train: Trainer/train.md
          - Dynamique du learning rate: Trainer/lr.md

  - Containers:
      - NeuralNetworks.Container:
          - Container/index.md
          - NeuralNetworks.Container.get: Container/get.md
          - Containers préfabriqués:
              - NeuralNetworks.norms: Container/norms.md
              - NeuralNetworks.crits: Container/crits.md
              - NeuralNetworks.optims: Container/optims.md


  - visuels:
      - NeuralNetworks.losses: UI/losses.md
      - NeuralNetworks.learnings: UI/learnings.md
plugins:
  - search:
      enabled: true
  - mkdocstrings:
      handlers:
          python:
            options:
              show_source: true
              source_url_template: "https://github.com/xXxFetraxXx/NeuralNetworks/blob/main/src/NeuralNetworks/{{ module_path }}.py#L{{ line }}"

copyright: Copyright &copy; 2025 - 2026 Alexandre Brun

extra:
  generator: false
  viewport: width=device-width, initial-scale=1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xXxFetraxXx/NeuralNetworks
      name: GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/NeuralNetworks/
      name: PyPI

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - tables
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg